name: Update Battleship Game

on:
  issues:
    types: [opened]

jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Update README
      run: |
        python update_readme.py "${{ github.event.issue.title }}"
     
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Update game state"
        git push
